// PhotoLynk Mobile App - Styles
import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const THEME = {
  bg: '#121212',
  card: '#1E1E1E',
  text: '#FFFFFF',
  textSec: '#AAAAAA',
  primary: '#BB86FC',
  secondary: '#03DAC6',
  error: '#CF6679'
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0A',
    paddingTop: Platform.OS === 'ios' ? 0 : 0,
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Auth Screen
  authHeader: {
    alignItems: 'center',
    marginTop: Math.max(40, SCREEN_HEIGHT * 0.08),
    marginBottom: Math.max(30, SCREEN_HEIGHT * 0.04),
  },
  appIcon: {
    width: Math.min(100, SCREEN_WIDTH * 0.25),
    height: Math.min(100, SCREEN_WIDTH * 0.25),
    borderRadius: 20,
    marginBottom: 16,
  },
  title: {
    fontSize: Math.min(32, SCREEN_WIDTH * 0.08),
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#AAAAAA',
    textAlign: 'center',
    paddingHorizontal: 30,
  },
  form: {
    paddingHorizontal: Math.max(20, SCREEN_WIDTH * 0.05),
    gap: 12,
    maxWidth: 500,
    width: '100%',
    alignSelf: 'center',
    marginBottom: 20,
  },
  input: {
    backgroundColor: '#1A1A1A',
    color: '#FFFFFF',
    padding: 18,
    borderRadius: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#333333',
  },
  btnPrimary: {
    backgroundColor: '#BB86FC',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    width: '100%',
    marginTop: 10,
  },
  btnSecondary: {
    padding: 18,
    alignItems: 'center',
  },
  btnText: {
    color: '#000000',
    fontWeight: 'bold',
    fontSize: 16,
  },
  btnDanger: {
    backgroundColor: '#7A1E2A',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    width: '100%',
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#CF6679',
  },
  btnDangerText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 15,
  },
  btnTextSec: {
    color: '#AAAAAA',
    fontSize: 16,
  },
  authFooter: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingBottom: 40,
  },
  footerText: {
    color: '#666666',
    fontSize: 12,
  },
  // Main Screen
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: '#0A0A0A',
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#888888',
    marginTop: 2,
  },
  logoutBtn: {
    backgroundColor: '#1A1A1A',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  logoutText: {
    color: '#FF6B6B',
    fontSize: 14,
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    flexGrow: 1,
    padding: Math.max(16, SCREEN_WIDTH * 0.04),
    maxWidth: 600,
    width: '100%',
    alignSelf: 'center',
  },
  statusCard: {
    backgroundColor: '#1A1A1A',
    padding: 20,
    borderRadius: 16,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  statusHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  statusLabel: {
    color: '#03DAC6',
    fontWeight: 'bold',
    fontSize: 12,
    letterSpacing: 2,
  },
  statusText: {
    color: '#FFFFFF',
    fontSize: 16,
    flexShrink: 1,
  },
  progressBar: {
    height: 6,
    backgroundColor: '#2A2A2A',
    borderRadius: 3,
    marginTop: 12,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#03DAC6',
  },
  actionsContainer: {
    flex: 1,
    gap: 12,
    marginBottom: 20,
  },
  actionCard: {
    flex: 1,
    padding: 16,
    borderRadius: 16,
    borderWidth: 2,
    justifyContent: 'center',
  },
  backupCard: {
    backgroundColor: '#2A1A3A',
    borderColor: '#BB86FC',
  },
  syncCard: {
    backgroundColor: '#0A2A2A',
    borderColor: '#03DAC6',
  },
  cleanupCard: {
    backgroundColor: '#2A240A',
    borderColor: '#FFB74D',
  },
  disabledCard: {
    opacity: 0.5,
  },
  overlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  overlayCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#1A1A1A',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#333333',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 12,
  },
  overlayTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  overlaySubtitle: {
    color: '#888888',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
    textAlign: 'center',
  },
  overlayBtnPrimary: {
    backgroundColor: THEME.primary,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 8,
    shadowColor: THEME.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  overlayBtnPrimaryText: {
    color: '#000000',
    fontWeight: '700',
    fontSize: 16,
  },
  overlayBtnSecondary: {
    backgroundColor: '#252525',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#3A3A3A',
  },
  overlayBtnSecondaryText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  overlayBtnGhost: {
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 12,
  },
  overlayBtnGhostText: {
    color: '#666666',
    fontSize: 15,
    fontWeight: '600',
  },
  pickerCard: {
    width: '100%',
    maxWidth: 650,
    maxHeight: '86%',
    backgroundColor: '#121212',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    overflow: 'hidden',
  },
  pickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#2A2A2A',
    backgroundColor: '#0A0A0A',
  },
  pickerHeaderBtn: {
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  pickerHeaderBtnText: {
    color: THEME.secondary,
    fontSize: 14,
    fontWeight: '700',
  },
  pickerHeaderTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  pickerHeaderSubtitle: {
    color: '#8A8A8A',
    fontSize: 12,
    marginTop: 2,
  },
  pickerGrid: {
    padding: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  pickerItem: {
    width: '32%',
    aspectRatio: 1,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 8,
    borderWidth: 2,
    borderColor: '#1A1A1A',
  },
  pickerItemSelected: {
    borderColor: THEME.secondary,
  },
  pickerThumb: {
    width: '100%',
    height: '100%',
  },
  pickerBadge: {
    position: 'absolute',
    left: 6,
    bottom: 6,
    backgroundColor: 'rgba(0,0,0,0.65)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  pickerBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
  },
  pickerCheck: {
    position: 'absolute',
    right: 6,
    top: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(3, 218, 198, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerCheckText: {
    color: '#000000',
    fontWeight: '900',
    fontSize: 14,
    includeFontPadding: false,
  },
  syncPickerList: {
    padding: 10,
  },
  syncPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: '#0A0A0A',
    borderWidth: 1,
    borderColor: '#2A2A2A',
    marginBottom: 10,
  },
  syncPickerRowSelected: {
    borderColor: THEME.secondary,
  },
  syncPickerRowLeft: {
    flex: 1,
    paddingRight: 12,
  },
  syncPickerRowTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 4,
  },
  syncPickerRowMeta: {
    color: '#8A8A8A',
    fontSize: 12,
  },
  syncPickerCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#1A1A1A',
    borderWidth: 1,
    borderColor: '#333333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  syncPickerCheckOn: {
    backgroundColor: 'rgba(3, 218, 198, 0.92)',
    borderColor: 'rgba(3, 218, 198, 0.92)',
  },
  syncPickerCheckText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 14,
  },
  syncPickerCheckTextOn: {
    color: '#000000',
  },
  cardIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  cardIconText: {
    fontSize: 24,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  cardDescription: {
    fontSize: Platform.select({
      ios: SCREEN_WIDTH < 380 ? 12 : 13,
      android: SCREEN_WIDTH < 380 ? 12 : 13,
      default: SCREEN_WIDTH < 380 ? 12 : 13,
    }),
    color: '#AAAAAA',
    lineHeight: SCREEN_WIDTH < 380 ? 17 : 18,
  },
  infoCard: {
    backgroundColor: '#1A1A1A',
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#03DAC6',
  },
  infoText: {
    color: '#AAAAAA',
    fontSize: 13,
  },
  // Server configuration
  serverConfig: {
    marginBottom: 20,
  },
  serverLabel: {
    color: '#AAAAAA',
    fontSize: 12,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  serverToggle: {
    flexDirection: 'row',
    gap: SCREEN_WIDTH < 380 ? 6 : 10,
    marginTop: 12,
  },
  serverExplanation: {
    marginTop: 12,
    padding: 12,
    backgroundColor: '#1A1A1A',
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: THEME.primary,
  },
  serverExplanationText: {
    color: '#CCCCCC',
    fontSize: 13,
    lineHeight: 20,
  },
  toggleBtn: {
    flex: 1,
    minHeight: SCREEN_WIDTH < 380 ? 40 : 44,
    paddingVertical: SCREEN_WIDTH < 380 ? 8 : 10,
    paddingHorizontal: SCREEN_WIDTH < 380 ? 6 : 10,
    borderRadius: 8,
    backgroundColor: '#1A1A1A',
    borderWidth: 2,
    borderColor: '#333333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleBtnActive: {
    backgroundColor: '#5E35B1',
    borderColor: '#BB86FC',
  },
  toggleText: {
    color: '#888888',
    fontSize: SCREEN_WIDTH < 380 ? 12 : 13,
    fontWeight: '600',
    textAlign: 'center',
    includeFontPadding: false,
  },
  toggleTextActive: {
    color: '#FFFFFF',
  },
  serverHint: {
    color: '#666666',
    fontSize: 12,
    marginTop: 8,
    textAlign: 'center',
  },
  // Settings screen
  settingsCard: {
    backgroundColor: '#1A1A1A',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    marginBottom: 16,
  },
  settingsTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  settingsDescription: {
    fontSize: 14,
    color: '#AAAAAA',
    marginBottom: 16,
  },
  uuidBox: {
    backgroundColor: '#0A0A0A',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  uuidLabel: {
    fontSize: 11,
    color: '#888888',
    marginBottom: 6,
  },
  uuidText: {
    fontSize: 11,
    color: '#03DAC6',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  inputLabel: {
    color: '#AAAAAA',
    fontSize: 14,
    marginBottom: 8,
    marginTop: 16,
  },
  inputHint: {
    color: '#666666',
    fontSize: 12,
    marginTop: 6,
    fontStyle: 'italic',
  },
  stealthPlanBox: {
    marginTop: 14,
    padding: 14,
    borderRadius: 14,
    backgroundColor: '#121212',
    borderWidth: 1,
    borderColor: '#2A2A2A',
  },
  stealthPlanHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  stealthPlanTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  stealthPlanHint: {
    color: '#8A8A8A',
    fontSize: 12,
    marginBottom: 10,
  },
  stealthPlanGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 0,
  },
  stealthPlanCard: {
    flexBasis: '25%',
    flexGrow: 0,
    flexShrink: 1,
    minWidth: 0,
    backgroundColor: '#1A1A1A',
    borderRadius: 10,
    padding: 6,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    minHeight: 70,
  },
  stealthPlanCardSelected: {
    borderColor: THEME.primary,
  },
  stealthPlanCardDisabled: {
    opacity: 0.55,
  },
  stealthPlanGb: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 4,
  },
  stealthPlanMeta: {
    color: '#AAAAAA',
    fontSize: 9,
    marginBottom: 6,
  },
  stealthPlanSoldOut: {
    color: '#FFB74D',
    fontSize: 11,
    lineHeight: 14,
  },
  stealthPlanPrice: {
    color: THEME.secondary,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 2,
  },
  usageGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  usageItem: {
    width: '50%',
    paddingRight: 10,
    marginBottom: 10,
  },
  restorePurchasesBtn: {
    marginTop: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  restorePurchasesText: {
    color: THEME.primary,
    fontSize: 14,
    fontWeight: '500',
  },
  serverInfo: {
    marginTop: 16,
    padding: 12,
    backgroundColor: '#0A0A0A',
    borderRadius: 8,
  },
  serverInfoLabel: {
    color: '#888888',
    fontSize: 11,
    marginBottom: 4,
  },
  serverInfoText: {
    color: '#9D9D9D',
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    flex: 1,
  },
  serverHelp: {
    marginTop: 16,
    padding: 14,
    backgroundColor: '#111111',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#222222',
  },
  serverHelpTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 8,
  },
  serverHelpSubtitle: {
    color: '#E0E0E0',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 6,
    marginBottom: 4,
  },
  serverHelpText: {
    color: '#B0B0B0',
    fontSize: 12,
    lineHeight: 18,
    marginLeft: 4,
  },
  headerButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  infoBtn: {
    backgroundColor: 'transparent',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
  },
  infoBtnText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#03DAC6',
  },
  settingsBtn: {
    backgroundColor: '#1A1A1A',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  settingsText: {
    fontSize: 20,
  },
  backBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  backText: {
    color: '#03DAC6',
    fontSize: 16,
  },
  // Setup Guide
  guideSteps: {
    marginTop: 16,
    gap: 16,
  },
  guideStep: {
    flexDirection: 'row',
    gap: 12,
  },
  stepNumber: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#5E35B1',
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: 32,
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  stepText: {
    color: '#AAAAAA',
    fontSize: 14,
    lineHeight: 20,
  },
  // How It Works
  howItWorksText: {
    color: '#CCCCCC',
    fontSize: 14,
    lineHeight: 22,
    marginTop: 12,
  },
  boldText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  setupGuideBtn: {
    backgroundColor: THEME.primary,
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    width: '100%',
    marginBottom: 12,
  },
  setupGuideBtnText: {
    color: '#000000',
    fontSize: 15,
    fontWeight: '600',
  },
  quickStepsTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  quickStepsText: {
    color: '#CCCCCC',
    fontSize: 13,
    lineHeight: 22,
  },
  linkList: {
    gap: 8,
    marginTop: 8,
  },
  linkButton: {
    backgroundColor: '#2A2A2A',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3A3A3A',
  },
  linkButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  codeLine: {
    color: '#FFFFFF',
    fontSize: 12,
    backgroundColor: '#1A1A1A',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginTop: 2,
  },
  codeHint: {
    color: '#888888',
    fontSize: 11,
    marginTop: 2,
  },
  guideStepNumber: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: THEME.primary,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    lineHeight: 32,
  },
  guideStepContent: {
    flex: 1,
  },
  guideStepTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 4,
  },
  guideStepDesc: {
    color: '#AAAAAA',
    fontSize: 13,
    lineHeight: 18,
  },
  copyLinkBtn: {
    backgroundColor: THEME.primary,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  copyLinkText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  // Resources
  resourceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#333333',
  },
  resourceIcon: {
    fontSize: 22,
    marginRight: 10,
  },
  resourceContent: {
    flex: 1,
  },
  resourceTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 2,
  },
  resourceDesc: {
    color: '#AAAAAA',
    fontSize: 12,
  },
  resourceArrow: {
    color: '#5E35B1',
    fontSize: 20,
    fontWeight: 'bold',
  },
  openSourceBadge: {
    backgroundColor: '#1A1A1A',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#5E35B1',
    marginTop: 6,
  },
  openSourceText: {
    color: '#BB86FC',
    fontSize: 12,
    textAlign: 'center',
    fontWeight: '600',
  },
  // Settings Footer
  settingsFooter: {
    alignItems: 'center',
    paddingVertical: 16,
    gap: 6,
  },
  footerVersion: {
    color: '#666666',
    fontSize: 12,
    textAlign: 'center',
  },
  footerCopyright: {
    color: '#666666',
    fontSize: 12,
  },
});
